// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2WFWfCUPthdM171CqFBM1t1Mt3qHVJtU',
    appId: '1:561040616522:web:cb96b3935c93fc304b0ab3',
    messagingSenderId: '561040616522',
    projectId: 'calendar-scheduler-9cd88',
    authDomain: 'calendar-scheduler-9cd88.firebaseapp.com',
    storageBucket: 'calendar-scheduler-9cd88.firebasestorage.app',
    measurementId: 'G-RBSBV4LK4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBobSJY30vbe4jk8MoXGMYHXAlnrbIfYIo',
    appId: '1:561040616522:android:e3d66a3dbfce0a954b0ab3',
    messagingSenderId: '561040616522',
    projectId: 'calendar-scheduler-9cd88',
    storageBucket: 'calendar-scheduler-9cd88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl_aDEu8j9VSjosbwJTFwHKpcROUIcrDI',
    appId: '1:561040616522:ios:b9a02645b75efdc84b0ab3',
    messagingSenderId: '561040616522',
    projectId: 'calendar-scheduler-9cd88',
    storageBucket: 'calendar-scheduler-9cd88.firebasestorage.app',
    androidClientId: '561040616522-89g6b0lbma42sabkra6fvm5q5nj64bna.apps.googleusercontent.com',
    iosClientId: '561040616522-cftn74r7941hpkt7g1ksvc5lm9n74i35.apps.googleusercontent.com',
    iosBundleId: 'com.hongmae.calendarScheduler',
  );

}