name: calendar_scheduler
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  supabase_flutter: ^2.9.0
  table_calendar: ^3.2.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
