// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWJ2Yk7wXc32PF-josZVuexMRp-WWwqak',
    appId: '1:1060292158063:android:35ccccd22964275fda239a',
    messagingSenderId: '1060292158063',
    projectId: 'bamtol-market-hongmae',
    storageBucket: 'bamtol-market-hongmae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmJMm-SU14kbSJ8iXIWex5NaAk3GSOKt8',
    appId: '1:1060292158063:ios:521c0e94f8f7eed4da239a',
    messagingSenderId: '1060292158063',
    projectId: 'bamtol-market-hongmae',
    storageBucket: 'bamtol-market-hongmae.firebasestorage.app',
    androidClientId: '1060292158063-2ed0rnuecltnuoelsrciaf9asi3d1nv5.apps.googleusercontent.com',
    iosClientId: '1060292158063-nuv083citn86jpslgl4gb0tnga5o7qte.apps.googleusercontent.com',
    iosBundleId: 'com.hongmae.cloneapp.bamtolMarketApp',
  );
}
